// <auto-generated />
namespace PerformanceTesting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class INSERT_INTO_TABLE_RunTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(INSERT_INTO_TABLE_RunTest));
        
        string IMigrationMetadata.Id
        {
            get { return "202001121209001_INSERT_INTO_TABLE_RunTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
