// <auto-generated />
namespace PerformanceTesting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class CREATE_TABLE_Message : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CREATE_TABLE_Message));
        
        string IMigrationMetadata.Id
        {
            get { return "202001120956304_CREATE_TABLE_Message"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
